### ISSUE TITLE
疐 and 𤴡

### ISSUE THREAD

**Issue by epistularum** [ichitenfont/inheritedglyphs#36]
Since this glyph's 部首 is 叀 I believe the inherited glyph should have the same shape as in 專 and not be 田+疋.
![image](https://user-images.githubusercontent.com/34507493/234181121-d4a784a9-1d8a-4b58-940a-03552c6d8f9b.png)

**Comment by TNTErick** [comment]
ccamc.org suggest that the upper part of 疐 , where the enclosure is more wide-shaped like 口, 田, 曰, is not the same as 叀, with a long-shaped enclosure like 東. You can even see the transition of 北 winding up to 冖 in 疐.

imo, 說文 is far from perfect to be a credible research material on its own. At the time it is composed (100~120 AD) the  隸書 script had been regulated for centuries and major evolution of Han characters happen ***before*** 200BC. Plus, lack of knowledge in linguistics and paleographic materials (they didn't know that their forefathers carved words into tortoise shells), numerous origins of characters were taken wrongly. Take 王 ("king") as an example, the 丨-through-三 shape was described as "一貫三爲王" (literally: they who have unified human, heaven and earth are able to be a king; he who have virtue can become a king) in 說文. However, long before this folk-etymology became popular, it was clear that 王 (and 士) was an axe, the symbol for power at the time.

**Comment by TNTErick** [comment]
Don't get me wrong, i think 說文 in a great source as it is more accessible and (comparatively) starter-friendly. In fact, in the Chinese Language and Literatures department of our uni, they still teach 說文 and 段玉裁's 說文解字注 in Paleography 1, and all others in Paleography 2. However after 19thc there are many more resources and archaeological materials to proof whether 許慎 was right.

**Comment by TNTErick** [comment]
The working group have awareness of the fact that 疐 doesn't consist 疋, we have no intention to such inference.

ccamc.org suggest that the upper part of 疐 , where the enclosure is more wide-shaped like 口, 田, 曰, is not the same as 叀, with a long-shaped enclosure like 東. You can even see the transition of 北 winding up to 冖 in 疐. There are not enough evidence to say confidently that 疐 have something to do with 叀, nor can we state what that component （疐-龰）is.

Actually the I.Font working group had had a discussion on it before, but since the paleography community doesn't come to a conclusion with what the upper part really is, we treat 疐 as a whole component and recommend the more prevailing one, which is described （十冖）+田+疋 as it is in the document.

P. S. imo, 說文 is far from perfect to be a credible research material on its own. At the time it is composed (100~120 AD) the  隸書 script had been regulated for centuries and major evolution of Han characters happen ***before*** 200BC. Plus, lack of knowledge in linguistics and paleographic materials (they didn't know that their forefathers carved words into tortoise shells), numerous origins of characters were interpreted differently from what we believe they to be, with 王, 愛, 憂, and 夏 as examples.Don't get me wrong, i think 說文 in a great source as it is more accessible and (comparatively) starter-friendly. However after 19thc there are many more resources and archaeological materials to compare with.

**Comment by epistularum** [comment]
I see, treating the whole character as a whole component makes sense. All 漢和 dictionaries I have (unfortunately I cannot speak chinese) treat it as 会意 but 白川静's 字通 actually treats the whole component as 象形. For some reason, Japanese dictionaries seem to insist that the correct shape is neither the one seen in 傳 nor the one seen in 疐 but rather a combination of the shapes ム+龰.
![image](https://user-images.githubusercontent.com/34507493/234449763-04165044-8962-4a9b-baa5-0b75bfd8ad8b.png)
(from 大漢和辞典)

It is worth noting that the first stroke of 疋 forms an opening but the shape seen in 疐 is completely closed, perhaps hinting to a different shape from 疋?
![image](https://user-images.githubusercontent.com/34507493/234451369-18e30bf1-381c-4d57-84cd-cbfd7ba6f992.png)

P.S.: Thank you very much for the detailed comment. It still amazes me that the discovery of 甲骨文 is extremely recent in the history of 漢字. Even if I cannot speak Chinese I would love to know if you have recommendations on reference material for semantic analysis. I already have plenty of 漢字 dictionaries in both chinese and Japanese and make use of online tools like the zi.tools dictionary explained in the pdf and I have added the above-mentioned ccamc.org to my resources list.
![image](https://user-images.githubusercontent.com/34507493/234452916-be24b8ba-5276-4f80-b01d-79253d60c597.png)
